package CriticalTools.ImageProcessing;

import CriticalTools.CommonForms.QuitForm;
import CriticalTools.Objects.ImageData;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;

/**
 *
 * @author Connor Rice
 */
public class ImageProcessingMainForm extends javax.swing.JFrame {
    private JFileChooser fc;

    /**
     * Creates new form ImageProcessingMainForm
     */
    public ImageProcessingMainForm(Component c) {
        initComponents();
        setLocationRelativeTo(c);
    }
    
    /**
     * Displays a JFileChooser that lets the user choose the directory with the
     * images to be in-processed.
     */
    private void openDirectory() {
        fc = new JFileChooser();
        fc.setCurrentDirectory(new java.io.File("."));
        fc.setDialogTitle("Choose a directory with image files...");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setAcceptAllFileFilterUsed(false);
        fc.setVisible(true);
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            imageList.setListData(parseImgNames(fc.getSelectedFile()));
        }
    }
    
    /**
     * Processes the image files that the user chooses from openDirectory()
     * @param inFile
     * @return 
     */
    private String[] parseImgNames(File inFile) {
        String[] imageStrings = new String[0];
        if (inFile.isDirectory()) {
            File[] curDirectory = inFile.listFiles();
            imageStrings = new String[curDirectory.length];
            for (int i = 0; i < curDirectory.length; i++) {
                imageStrings[i] = curDirectory[i].getName();
            }
        }
        return imageStrings;
    }
    
    public void addPage() {
        
    }
    
    public String getImgType(String[] fileNames) {
        String imgType = "";
        for (String s : fileNames) {
            String[] sa = s.split("_");
            imgType += sa[1].charAt(0);
        }
        return imgType;
    }
    
    public ImageData createImageData(int startMeasure, int endMeasure, 
            int pageNumber, String imgType) {
        return new ImageData(startMeasure, endMeasure, pageNumber, imgType);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        imageList = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openDirectoryItem = new javax.swing.JMenuItem();
        quitButton = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Critical Tools - Image Processing");

        imageList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(imageList);

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        openDirectoryItem.setText("Open directory...");
        openDirectoryItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDirectoryItemActionPerformed(evt);
            }
        });
        fileMenu.add(openDirectoryItem);

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        fileMenu.add(quitButton);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");
        jMenuBar1.add(editMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        new QuitForm(this).setVisible(true);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void openDirectoryItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDirectoryItemActionPerformed
        // TODO add your handling code here:
        openDirectory();
    }//GEN-LAST:event_openDirectoryItemActionPerformed

    private void imageListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageListMouseClicked
        if (evt.getButton() == (MouseEvent.BUTTON3)) {
            List selectedValues = imageList.getSelectedValuesList();
            String[] selectedString = new String[selectedValues.size()];
            for (int i = 0; i < selectedValues.size(); i++) {
                selectedString[i] = (String) selectedValues.get(i);
            }
            System.out.println(getImgType(selectedString));
        }
    }//GEN-LAST:event_imageListMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JList imageList;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem openDirectoryItem;
    private javax.swing.JMenuItem quitButton;
    // End of variables declaration//GEN-END:variables
}
