package CriticalTools.MeasureLocator;

import CriticalTools.Objects.SearchResult;

/**
 *
 * @author Connor Rice
 */
public class ImageUtilsForm extends javax.swing.JFrame {
    private ImageForm imgForm;
    private SearchResult searchResult;

    /**
     * Creates new form ImageUtilsForm
     */
    public ImageUtilsForm(ImageForm imgForm, SearchResult searchResult) {
        this.imgForm = imgForm;
        this.searchResult = searchResult;
        initComponents();
        renameLabels();
    }
    
    private void renameLabels() {
        startingLabel.setText("Starting Measure: " + Integer.toString(searchResult.getMeasureRange()[0]));
        endingLabel.setText("Ending Measure: " + Integer.toString(searchResult.getMeasureRange()[1]));
        //searchedMeasureLabel.setText("Searched Measure: ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        startingLabel = new javax.swing.JLabel();
        endingLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Utilities");

        nextButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Previous");

        startingLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        startingLabel.setText("Starting Measure:");

        endingLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        endingLabel.setText("Ending Measure:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startingLabel)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(nextButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(endingLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startingLabel)
                .addGap(15, 15, 15)
                .addComponent(endingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextButtonActionPerformed

    @Override
    public void dispose() {
        super.dispose();
        imgForm.closeExternal();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel endingLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel startingLabel;
    // End of variables declaration//GEN-END:variables
}
