package CriticalTools;

import CriticalTools.CommonForms.AboutForm;
import CriticalTools.CommonForms.QuitForm;
import CriticalTools.DatabaseManagement.DatabaseManagementMainForm;
import CriticalTools.ImageProcessing.ImageProcessingMainForm;
import CriticalTools.MeasureComparison.MeasureComparisonMainForm;
import CriticalTools.Util.ImageHandler;

/**
 * The main GUI for selecting which application within the suite should be
 * accessed.
 *
 * @author Connor Rice
 */
public class MainGUI extends javax.swing.JFrame {

    private ImageHandler pOps;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    protected void quit() {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appComboBox = new javax.swing.JComboBox();
        okayButton = new javax.swing.JButton();
        appLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        quitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpMenuDocItem = new javax.swing.JMenuItem();
        helpMenuAboutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Critical Tools Alpha");

        appComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Measure Finder", "Measure Comparison", "Image Processing", "Database Management" }));
        appComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appComboBoxActionPerformed(evt);
            }
        });

        okayButton.setText("Okay");
        okayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okayButtonActionPerformed(evt);
            }
        });

        appLabel.setText("Select Application: ");

        fileMenu.setText("File");

        quitMenuItem.setText("Quit");
        quitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(quitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText("Help");

        helpMenuDocItem.setText("Documentation...");
        helpMenu.add(helpMenuDocItem);

        helpMenuAboutItem.setText("About");
        helpMenuAboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuAboutItemActionPerformed(evt);
            }
        });
        helpMenu.add(helpMenuAboutItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okayButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(appLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(appComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appLabel))
                .addGap(18, 18, 18)
                .addComponent(okayButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appComboBoxActionPerformed
    }//GEN-LAST:event_appComboBoxActionPerformed

    private void okayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okayButtonActionPerformed
        int selIndex = appComboBox.getSelectedIndex();
        if (selIndex == 0) {
            pOps = new ImageHandler(this);
        } else if (selIndex == 1) {
            new MeasureComparisonMainForm(this).setVisible(true);
        } else if (selIndex == 2) {
            new ImageProcessingMainForm(this).setVisible(true);
        } else if (selIndex == 3) {
            new DatabaseManagementMainForm(this).setVisible(true);
        }
    }//GEN-LAST:event_okayButtonActionPerformed

    private void helpMenuAboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuAboutItemActionPerformed
        new AboutForm(this).setVisible(true);
    }//GEN-LAST:event_helpMenuAboutItemActionPerformed

    private void quitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMenuItemActionPerformed
        new QuitForm(this).setVisible(true);
    }//GEN-LAST:event_quitMenuItemActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox appComboBox;
    private javax.swing.JLabel appLabel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuAboutItem;
    private javax.swing.JMenuItem helpMenuDocItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton okayButton;
    private javax.swing.JMenuItem quitMenuItem;
    // End of variables declaration//GEN-END:variables
}
