package CriticalTools.CommonForms;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import CriticalTools.Objects.SearchResult;
import CriticalTools.Util.ImageOps;
import java.awt.Component;

/**
 * Form for displaying images.
 * TODO: Move image operations to ImageOps java
 * @author Connor Rice
 */
public class ImageForm extends javax.swing.JFrame {

    private BufferedImage originalImage;
    private BufferedImage currentImage;
    private SearchResult searchResult;
    private ImageOps iIO;

    public ImageForm(SearchResult searchResult, Component c) throws IOException {
        this.searchResult = searchResult;
        this.iIO = new ImageOps(searchResult);
        initComponents();
        iIO.readImage();
        initImage();
        setLocationRelativeTo(c);
        setTitle(iIO.getFormattedTitle());
        
    }
    
    private void initImage() {
        jLabel1.setIcon(iIO.scaleImage());
        int[] bounds = iIO.getImageBounds();
        this.setBounds(bounds[0], bounds[1], bounds[2], bounds[3]);
    }
    

    @Override
    public void dispose() {
        super.dispose();
    }
    
    public void closeExternal() {
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 300, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
